# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 01:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpoProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project1', models.BooleanField()),
                ('project2', models.BooleanField()),
                ('project3', models.BooleanField()),
                ('project4', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(blank=True, upload_to=b'./mainsite/static/')),
                ('username', models.CharField(default=b'Username', max_length=20)),
                ('name', models.CharField(blank=True, default=b'Name', max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('branch', models.CharField(blank=True, choices=[(b'First Year', b'First Year'), (b'Second Year', b'Second Year'), (b'Third Year', b'Third Year'), (b'Final Year', b'Final Year'), (b'Alumni', b'Alumni')], default=b'First Year', max_length=11)),
                ('work', models.CharField(blank=True, default=b'Company/University', max_length=50)),
                ('DOB', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('year', models.CharField(blank=True, default=b'Year', max_length=12)),
                ('bio', models.TextField(blank=True, default=b'Lorem ipsum sit dolot fuck this shit !')),
                ('linkedin', models.URLField(blank=True)),
                ('resume', models.FileField(blank=True, upload_to=b'./mainsite/static')),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(blank=True, upload_to=b'')),
                ('name', models.CharField(default=b'Name', max_length=50)),
                ('description', models.TextField(default=b'Shitty Project')),
                ('github', models.URLField(blank=True)),
                ('completed', models.BooleanField()),
                ('contributers', models.CharField(default=b'dev', max_length=100)),
            ],
        ),
    ]
