# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-15 17:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to=b'')),
                ('username', models.CharField(default=b'Username', max_length=20)),
                ('password', models.CharField(default=b'Password', max_length=20)),
                ('name', models.CharField(default=b'Name', max_length=50)),
                ('email', models.EmailField(default=b'e-mail', max_length=254)),
                ('branch', models.CharField(default=b'Branch', max_length=50)),
                ('work', models.CharField(default=b'Company/University', max_length=50)),
                ('DOB', models.DateField(default=datetime.datetime(2016, 6, 15, 17, 3, 37, 873205, tzinfo=utc))),
                ('year', models.CharField(default=b'Year', max_length=12)),
                ('bio', models.TextField(default=b'Lorem ipsum sit dolot fuck this shit !')),
                ('linkedin', models.URLField(null=True)),
                ('resume', models.FileField(null=True, upload_to=b'')),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
