# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-19 19:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_auto_20160616_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='DOB',
            field=models.DateField(default=datetime.datetime(2016, 6, 19, 19, 26, 30, 987840, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='member',
            name='pic',
            field=models.ImageField(upload_to=b'./mainsite/static/'),
        ),
        migrations.AlterField(
            model_name='member',
            name='resume',
            field=models.FileField(null=True, upload_to=b'./mainsite/static'),
        ),
    ]
