# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-20 17:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0009_auto_20160620_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.EmailField(default=b'e-mail', max_length=254),
        ),
        migrations.AddField(
            model_name='member',
            name='password',
            field=models.CharField(default=b'Password', max_length=20),
        ),
        migrations.AddField(
            model_name='member',
            name='username',
            field=models.CharField(default=b'Username', max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='DOB',
            field=models.DateField(default=datetime.datetime(2016, 6, 20, 17, 39, 56, 39838, tzinfo=utc)),
        ),
    ]
