# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-20 18:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0011_auto_20160620_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='DOB',
            field=models.DateField(default=datetime.datetime(2016, 6, 20, 18, 1, 21, 756067, tzinfo=utc)),
        ),
    ]
