# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-20 18:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0015_auto_20160620_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='DOB',
            field=models.DateField(default=datetime.datetime(2016, 6, 20, 18, 24, 12, 545825, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='bio',
            field=models.TextField(default=b'Lorem ipsum sit dolot fuck this shit !', null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='branch',
            field=models.CharField(default=b'Branch', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='pic',
            field=models.ImageField(null=True, upload_to=b'./mainsite/static/'),
        ),
        migrations.AlterField(
            model_name='member',
            name='work',
            field=models.CharField(default=b'Company/University', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='year',
            field=models.CharField(default=b'Year', max_length=12, null=True),
        ),
    ]
