# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-20 18:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0016_auto_20160620_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='DOB',
            field=models.DateField(default=datetime.datetime(2016, 6, 20, 18, 24, 16, 233869, tzinfo=utc), null=True),
        ),
    ]
