# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 18:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0017_auto_20160620_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='DOB',
            field=models.DateField(default=datetime.datetime(2016, 6, 20, 18, 35, 44, 145869, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='bio',
            field=models.TextField(default='Lorem ipsum sit dolot fuck this shit !', null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='branch',
            field=models.CharField(default='Branch', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(default='e-mail', max_length=254),
        ),
        migrations.AlterField(
            model_name='member',
            name='password',
            field=models.CharField(default='Password', max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='pic',
            field=models.ImageField(null=True, upload_to='./mainsite/static/'),
        ),
        migrations.AlterField(
            model_name='member',
            name='username',
            field=models.CharField(default='Username', max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='work',
            field=models.CharField(default='Company/University', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='year',
            field=models.CharField(default='Year', max_length=12, null=True),
        ),
    ]
