# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 11:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0017_auto_20160620_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='DOB',
            field=models.DateField(default=datetime.datetime(2016, 6, 21, 11, 18, 1, 5000, tzinfo=utc), null=True),
        ),
    ]
