# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 20:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0018_auto_20160621_0005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='password',
        ),
        migrations.AlterField(
            model_name='member',
            name='DOB',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 6, 20, 20, 23, 53, 462100, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='member',
            name='bio',
            field=models.TextField(blank=True, default='Lorem ipsum sit dolot fuck this shit !'),
        ),
        migrations.AlterField(
            model_name='member',
            name='branch',
            field=models.CharField(blank=True, default='Branch', max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='member',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(blank=True, default='Name', max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='pic',
            field=models.ImageField(blank=True, upload_to='./mainsite/static/'),
        ),
        migrations.AlterField(
            model_name='member',
            name='resume',
            field=models.FileField(blank=True, upload_to='./mainsite/static'),
        ),
        migrations.AlterField(
            model_name='member',
            name='work',
            field=models.CharField(blank=True, default='Company/University', max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='year',
            field=models.CharField(blank=True, default='Year', max_length=12),
        ),
    ]
