# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 07:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0019_auto_20160621_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='DOB',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 6, 21, 7, 16, 23, 290992, tzinfo=utc)),
        ),
    ]
