# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-21 17:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0023_auto_20160621_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='DOB',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 6, 21, 17, 53, 15, 881558, tzinfo=utc)),
        ),
    ]
