# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-21 18:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0024_auto_20160621_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='DOB',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 6, 21, 18, 4, 9, 110803, tzinfo=utc)),
        ),
    ]
