# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-21 18:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0025_auto_20160621_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='DOB',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 6, 21, 18, 7, 56, 411632, tzinfo=utc)),
        ),
    ]
