# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 20:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0028_auto_20160622_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='DOB',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 6, 23, 20, 37, 35, 175539, tzinfo=utc)),
        ),
    ]
