# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 04:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0042_auto_20160624_0411'),
        ('mainsite', '0018_auto_20160621_1648'),
    ]

    operations = [
    ]
