# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 04:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0043_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='DOB',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
