# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 21:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0044_auto_20160624_0944'),
        ('mainsite', '0045_auto_20160624_2108'),
    ]

    operations = [
    ]
