# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-25 16:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0047_auto_20160625_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='DOB',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 6, 25, 16, 34, 41, 842983, tzinfo=utc)),
        ),
    ]
