# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-25 18:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0049_auto_20160625_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='DOB',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 6, 25, 18, 22, 20, 924733, tzinfo=utc)),
        ),
    ]
