# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-25 19:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0051_auto_20160626_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='DOB',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 6, 25, 19, 40, 25, 600173, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='member',
            name='branch',
            field=models.CharField(blank=True, choices=[('First Year', 'First Year'), ('Second Year', 'Second Year'), ('Third Year', 'Third Year'), ('Final Year', 'Final Year'), ('Alumni', 'Alumni')], default='First Year', max_length=11),
        ),
    ]
