# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 20:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0053_auto_20160626_0142'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpoProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project1', models.BigIntegerField(default=0)),
                ('project2', models.BigIntegerField(default=0)),
                ('project3', models.BigIntegerField(default=0)),
                ('project4', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='member',
            name='DOB',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 6, 26, 20, 53, 25, 650619, tzinfo=utc)),
        ),
    ]
